### ISSUE TITLE
Doesn't compile

### ISSUE THREAD

**Issue by Nicholaiii** [firestar115/finalterm-reborn#2]
`undefined reference to 'gtk_widget_set_focus_on_click'`

commenting out the reference makes it build, compile and run fine. assuming this is because of a deprecated attribute.

**Comment by firestar115** [comment]
Probably because of your GTK version, worked fine on GTK 3.12

**Comment by Nicholaiii** [comment]
Yes, I think that's exactly it, however, googling a bit revealed that the attribute is indeed deprecated and GTK doesnt support this anymore, so for forward compatibility it shouldn't be used :)

**Comment by firestar115** [comment]
Create a pull request ;)
